server:
  port: 5555

spring:
  application:
    name: API-Gateway-1

  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: authservice-api
              uri: lb://AUTHSERVICE
              predicates:
                - Path=/auth/**
              filters:
                - RewritePath=/auth/(?<segment>.*), /${segment}

            - id: microservice-api
              uri: lb://MICROSERVICE1-PROJECT
              predicates:
                - Path=/micro1/**
              filters:
                - RewritePath=/micro1/(?<segment>.*), /${segment}
