server:
  port: 5555

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: microservice-api-1
              uri: lb://MICROSERVICE-1
              predicates:
                - Path=/micro1/**
              filters:
                - RewritePath=/micro1/(?<segment>.*), /${segment}

            - id: microservice-api-2
              uri: lb://MICROSERVICE-2
              predicates:
                - Path=/micro2/**
              filters:
                - RewritePath=/micro2/(?<segment>.*), /${segment}
