package com.bookingservice.entity;
// Declares the package this class belongs to.

import jakarta.persistence.*;
// Imports JPA annotations for ORM mapping.

@Entity
// Marks this class as a JPA entity to be mapped to a database table.

@Table(name="bookings")
// Specifies the database table name as "bookings".

public class Bookings {
// Defines the public class named Bookings representing a booking entity.

    @Id
    // Marks this field as the primary key of the entity.

    @GeneratedValue(strategy = GenerationType.IDENTITY)
    // Specifies that the primary key value is auto-generated by the database using identity strategy.

    private long id;
    // Private field to store the unique identifier of the booking.

    private String name;
    // Private field to store the name of the person who made the booking.

    private String email;
    // Private field to store the email address of the person who made the booking.

    private String mobile;
    // Private field to store the mobile number of the person who made the booking.

    private String propertyName;
    // Private field to store the name of the property that is booked.

    private double totalPrice;
    // Private field to store the total price of the booking.

    private String status;
    // Private field to store the status of the booking (e.g., confirmed, cancelled).

    // Getter method for 'id' field.
    public long getId() {
        return id;
    }

    // Getter method for 'name' field.
    public String getName() {
        return name;
    }

    // Getter method for 'email' field.
    public String getEmail() {
        return email;
    }

    // Getter method for 'mobile' field.
    public String getMobile() {
        return mobile;
    }

    // Getter method for 'propertyName' field.
    public String getPropertyName() {
        return propertyName;
    }

    // Getter method for 'totalPrice' field.
    public double getTotalPrice() {
        return totalPrice;
    }

    // Getter method for 'status' field.
    public String getStatus() {
        return status;
    }

    // Setter method for 'id' field.
    public void setId(long id) {
        this.id = id;
    }

    // Setter method for 'name' field.
    public void setName(String name) {
        this.name = name;
    }

    // Setter method for 'email' field.
    public void setEmail(String email) {
        this.email = email;
    }

    // Setter method for 'mobile' field.
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    // Setter method for 'propertyName' field.
    public void setPropertyName(String propertyName) {
        this.propertyName = propertyName;
    }

    // Setter method for 'totalPrice' field.
    public void setTotalPrice(double totalPrice) {
        this.totalPrice = totalPrice;
    }

    // Setter method for 'status' field.
    public void setStatus(String status) {
        this.status = status;
    }
}
